version: "3.8"

services:
  client:
    build: ..
    image: benefits_client:latest
    env_file: .env
    ports:
      - "${DJANGO_LOCAL_PORT}:8000"
    volumes:
      - ../.aws/config:/home/calitp/app/config:ro
      - ../fixtures:/home/calitp/app/fixtures:ro

  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    image: benefits_client:dev
    env_file: .env
    # https://code.visualstudio.com/docs/remote/create-dev-container#_use-docker-compose
    entrypoint: sleep infinity
    depends_on:
      - server
    ports:
      - "${DJANGO_LOCAL_PORT}:8000"
    volumes:
      - ../:/home/calitp/app

  docs:
    image: benefits_client:dev
    entrypoint: mkdocs
    command: serve --dev-addr "0.0.0.0:8000"
    ports:
      - "8001:8000"
    volumes:
      - ../:/home/calitp/app

  server:
    image: ghcr.io/cal-itp/eligibility-server@sha256:337d5b2beb1e458980be49a778efd4a47f8daa8decc5e8329c0d528596e2f196
    ports:
      - "5000"

  s3pull:
    image: amazon/aws-cli
    entrypoint: [ "/bin/sh" ]
    command: [ "-c", "aws s3 sync s3://${AWS_BUCKET} ." ]
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
    volumes:
      - ../.aws/config:/aws

  s3push:
    image: amazon/aws-cli
    entrypoint: [ "/bin/sh" ]
    command: [ "-c", "aws s3 sync . s3://${AWS_BUCKET}" ]
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
    volumes:
      - ../.aws/config:/aws
